### PR TITLE
Enable Download section

### PR DESCRIPTION
**Pull request by edespino**
@jacksoncvm - I reviewed this with Roman and he is fine with enabling the Download section.  Please review this pull request with a slightly adjusted version.
- Enable Download section
- Add valid link values for HAWQ 2.0.0.0 have been provided.
- Rename SHA to SHA-256
- Rename OpenPGP to PGP

### CODE REVIEW

**Review by jacksoncvm — COMMENTED** [review]
Looks fine to me.  Not sure we need this part? (circa line 88)

<div class="button-container">
          <a class="button" href="#download">DOWNLOAD<small class="download-version">Version #</small></a>
       </div>

**Comment by edespino** [comment]
@jacksoncvm - I removed the section you suggested.

**Comment by edespino** [comment]
@jacksoncvm - Do you mind if I push these changes?

**Comment by jacksoncvm** [comment]
That would be great - thank you!

-Chloe

**Pull request closed without merging**
