### PR TITLE
Fix the issue that the Download part looks confusing.

### PR DESCRIPTION
**Pull request by paul-guo-**
Especially consider we will have the binary release.

I'm fixing by referring the Apache couchdb home page, but with some differences.

Thanks for the gpdb gpcc team for helping some style issues.

### CODE REVIEW

**Comment by paul-guo-** [comment]
@dyozie @edespino @rvs 
Anyone could help me to review this change? Thanks.

**Comment by dyozie** [comment]
This looks like an improvement to me - thanks!

**Comment by edespino** [comment]
The Apache HAWQ incubating site is based on Apache CouchDB (http://couchdb.apache.org/). Personally, I like their download icons which we may want to add to our download section for additional clarity. Their repo is located here https://github.com/apache/couchdb-www in the branch asf-site.  Please consider adding the download icons in this PR.

**Comment by paul-guo-** [comment]
@edespino personally I agree with your idea, however I could not find the icon from the repo. Finally I consulted with some guys know web development, and they told me that the CouchDB homepage uses  the so-called sprite.png which merges a lot of small pic into one large pic. I'm not really an frontend expert so I'm wondering someone else could help on this or do it in the future.

**Comment by edespino** [comment]
I have a fix for the sprite icons on my local system.  Would you mind if I push my changes to your dev branch (paul-guo-:download)?

**Comment by paul-guo-** [comment]
@edespino. No problem.

**Comment by paul-guo-** [comment]
@edespino checked in another one which includes this fix, so I'm closing this PR.

**Pull request closed without merging**
