### PR TITLE
Link doc to the open source version and move the docs link right befo…

### PR DESCRIPTION
**Pull request by paul-guo-**
…re "More..."

### CODE REVIEW

**Comment by paul-guo-** [comment]
Doc links to the latest version. I guess we should add links to all versions in each doc also?

**Comment by paul-guo-** [comment]
@rvs @dyozie , Any comment? Or who should I get comments from? Thanks.

**Comment by dyozie** [comment]
We currently don't have a landing page at docs/userguide/latest/index.html, but I can add a redirect there to point to /docs/userguide/2.1.0.0-incubating/ (or whichever the latest version happens to be).  Does that sound ok?

**Comment by paul-guo-** [comment]
@dyozie 
It looks better.

**Comment by dyozie** [comment]
@paul-guo- the redirect file at http://hawq.incubator.apache.org/docs/userguide/latest/index.html is now in place, so feel free to merge this PR as soon as 2.1.0.0 is official.

**Comment by paul-guo-** [comment]
Patch Merged. Closing the PR.

**Pull request closed without merging**
